import mysql.connector as c

# Establish the connection to SQL
myconn = c.connect(host="localhost", user="root", password="1234")
mycur = myconn.cursor()

# Create the database if it doesn't exist
mycur.execute("CREATE DATABASE IF NOT EXISTS Prod_Reccomend_Sys")

# Connect to Database now after Database has been created
myconn = c.connect(host="localhost", user="root", password="1234", database="Prod_Reccomend_Sys")
mycur = myconn.cursor()

# Create User Login table
query1 = '''CREATE TABLE IF NOT EXISTS User_Login (
    uID INT PRIMARY KEY,
    Name VARCHAR(30),
    Email_ID VARCHAR(20),
    Contact_No CHAR(14),
    Password VARCHAR(15)
)'''
mycur.execute(query1)

# Create Content Store table that Stores Data Which Is extracted By Internet
query2 = '''CREATE TABLE IF NOT EXISTS Content_Store (
    ContentID INT PRIMARY KEY,
    Type VARCHAR(30),
    Title VARCHAR(100),
    Genre VARCHAR(100),
    Description TEXT,
    WebRatings FLOAT
)'''
mycur.execute(query2)

""" Now Create the ML RECCOMENDATION table ( when ML Model Is Trained and Provided with data from contentTable Output Generated by
    by that Model is stored in this Table later from which required output is given to user
"""

query3 = '''CREATE TABLE IF NOT EXISTS ML_RECCOMENDATION (
    Reccomendation_ID INT PRIMARY KEY,
    uID INT,
    ContentID INT,
    Score FLOAT,
    Description TEXT,
    FOREIGN KEY (uID) REFERENCES User_Login(uID),
    FOREIGN KEY (ContentID) REFERENCES Content_Store(ContentID)
)'''
mycur.execute(query3)

# Create the User Reviews table ( when User Has received output He/she will be Provided with review option to Rate ML Model and suggest changes 
query4 = '''CREATE TABLE IF NOT EXISTS User_Reviews (
    Review_ID INT PRIMARY KEY,
    uID INT,
    ContentID INT,
    Ratings INT,
    Comment TEXT,
    FOREIGN KEY (uID) REFERENCES User_Login(uID),
    FOREIGN KEY (ContentID) REFERENCES Content_Store(ContentID)
)'''
mycur.execute(query4)

# Close the cursor and connection
mycur.close()
myconn.close()
